//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : WriteScoreService.java
//  @ Date : 2020/6/30
//  @ Author : 
//
//




public interface WriteScoreService {
	public void findMajor();
	public void writeStuScore();
	public void findStudent();
}
