//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : WriteScoreServiceImpl.java
//  @ Date : 2020/6/30
//  @ Author : 
//
//




public class WriteScoreServiceImpl implements WriteScoreService {
    public void findMajor()
    {
        System.out.println("findMajor");
    }
    public void writeStuScore()
    {
        System.out.println("writeStuScore");
    }
    public void findStudent()
    {
        System.out.println("findStudent");
    }
}
