//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : examDaoImpl.java
//  @ Date : 2020/6/30
//  @ Author : 
//
//




public class examDaoImpl implements examDao 
{
    public void selectAllExam()
    {
        System.out.println("selectAllExam");
    }
}
