//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : examDao.java
//  @ Date : 2020/6/30
//  @ Author : 
//
//




public interface examDao {
	public void selectAllExam();
}
