//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : nameExamDaoImpl.java
//  @ Date : 2020/6/30
//  @ Author : 
//
//




public class nameExamDaoImpl implements nameExamDao {
    public void selectNameExam()
    {
        System.out.println("selectNameExam");
    }
}
