//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : nameExamDao.java
//  @ Date : 2020/6/30
//  @ Author : 
//
//




public interface nameExamDao {
	public void selectNameExam();
}
