//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : noteController.java
//  @ Date : 2020/6/30
//  @ Author : 
//
//




public class noteController {
	public void showTextOfExam() {
	
	}
	
	public void showNameText() {
	
	}
	
	public void sendNote() {
	
	}
}
