//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NoteServiceImpl.java
//  @ Date : 2020/6/30
//  @ Author : 
//
//




public class NoteServiceImpl implements NoteService {
    public void findExam()
    {
        System.out.println("findExam");
    }
    public void findNameExam()
    {
        System.out.println("findNameExam");
    }
    public void note()
    {
        System.out.println("note");
    }
}
