//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NoteService.java
//  @ Date : 2020/6/30
//  @ Author : 
//
//




public interface NoteService {
	public void findExam();
	public void findNameExam();
	public void note();
}
