//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : studentImpl.java
//  @ Date : 2020/6/30
//  @ Author : 
//
//




public class studentImpl implements studentDao {
    public void selectAllStuForMajor()
    {
        System.out.println("selectAllStuForMajor");
    }
}
