//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : studentDao.java
//  @ Date : 2020/6/30
//  @ Author : 
//
//




public interface studentDao {
	public void selectAllStuForMajor();
}
