//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : stuNoteDaoImpl.java
//  @ Date : 2020/6/30
//  @ Author : 
//
//




public class stuNoteDaoImpl implements stuNoteDao {
    public void noteUpdate()
    {
        System.out.println("noteUpdate");
    }
}
