//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : stuNoteDao.java
//  @ Date : 2020/6/30
//  @ Author : 
//
//




public interface stuNoteDao {
	public void noteUpdate();
}
